# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
