# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_magic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20)),
            ],
        ),
    ]
