# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_loginrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('view', models.CharField(max_length=5)),
                ('authorid', models.CharField(max_length=10)),
            ],
        ),
    ]
