# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20161025_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iconUrl_large',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='iconUrl_middle',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='iconUrl_small',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
