# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20161025_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='iconUrl_large',
        ),
        migrations.RemoveField(
            model_name='user',
            name='iconUrl_middle',
        ),
    ]
